version: '3'
services:
  fe:
    build:
      context: .
    working_dir: /app/cctiv_fe
    ports:
      - "5173:5173"
    volumes:
      - "./cctiv_fe:/app/cctiv_fe"
    command: >
      sh -c "npm run dev"